// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarListApp.Api.Migrations
{
    [DbContext(typeof(CarListDbContext))]
    partial class CarListDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.8");

            modelBuilder.Entity("Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Vin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Make = "Ford",
                            Model = "Mustang",
                            Vin = "1967"
                        },
                        new
                        {
                            Id = 2,
                            Make = "Honda",
                            Model = "2000",
                            Vin = "2004"
                        },
                        new
                        {
                            Id = 3,
                            Make = "Toyota",
                            Model = "Supra",
                            Vin = "2000"
                        },
                        new
                        {
                            Id = 4,
                            Make = "Dodge",
                            Model = "Charger",
                            Vin = "1994"
                        },
                        new
                        {
                            Id = 5,
                            Make = "Ferrari",
                            Model = "V70",
                            Vin = "2020"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
